### ISSUE TITLE
HeroHours front end rolls over when a user passes 100 hours

### ISSUE THREAD

**Issue by memtech3** [FRC5892/HeroHours#3]
HeroHours front end displays hours in the 100s as numbers that are not in the 100s (ex: 101 = 1, 100 = 0, 150 = 50)

**Comment by MichaelStatt-S** [comment]
appears to be related to [this](https://github.com/FRC5892/HeroHours/blob/000f1b9e73942924447ff8604841debcaf33a403/hours.js#L200) line. 

This would probably fix it
```js
('0' + h).slice(-2); /*->*/ (h < 10 ? '0' : '') + h;
```
Ill fix it when I get edit access

**Comment by MichaelStatt-S** [comment]
Fixed in rewrite

**Comment by memtech3** [comment]
Cool!
