### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by yyy2356** [FRC5892/HeroHours#31]
Change total_hours to a duration field and change all the views and anything that references it to accommodate that.

**Comment by yyy2356** [comment]
only you have had your total hours cutoff by this, so we need to fix your time. the total seconds has it backed up, luckily.

**Comment by yyy2356** [comment]
I think that maybe only the model needed to be changed, luckily. Everything seems to be working after doing the migration on development.

**Comment by MichaelStatt-S** [comment]
1 i made a branch for you
2 why don't we just get rid of that all together? We are storing the same value twice. I say just use the total seconds

**Comment by yyy2356** [comment]
There was probably some reason... maybe it was just copied over from the original and they needed it for some reason that isn't relevant anymore. Storing it twice might be a good idea anyways for redundancy, and all the infrastructure for it is set up. The change was pretty simple.

**Comment by yyy2356** [comment]
my current pr should fix it, less changes needed to be made than i thought as django is pretty resilient.

**Comment by yyy2356** [comment]
i overestimated the difficulty, all that needs to happen is fixing your total hours and implementing the changes made in the pr before todays meeting.
