### ISSUE TITLE
Logs list in admin

### ISSUE THREAD

**Issue by yyy2356** [FRC5892/HeroHours#39]
Speed up the logs list in admin view. It is currently extremely slow.

**Comment by yyy2356** [comment]
Its slow because the db is being accessed repeatedly to display the logs, i believe. issue is in the get_name function

**Comment by MichaelStatt-S** [comment]
It think this can be solved by using relationships in Django 
see https://docs.djangoproject.com/en/5.1/topics/db/examples/many_to_one/
